name = "Packwiz Test"
author = "lorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f8ece0bd3757471ef51c87781438f08ba48c404f944078283d04313922fc414"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
datapack-folder = "config/paxi/resourcepacks"
