name = "Packwiz Test"
author = "lorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fb709ffbdc96d773d4389beb11e67df21325fc2df20f212e4a4dec4f6c378d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
