name = "Packwiz Test"
author = "lorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4923d6a0d239c27f2e52d772b6bfe4f436f85d2ac98cc5892199703988502b4c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
